In [ ]:
sales 1.csv
products.csv
customers.json

SyntaxError: invalid decimal literal (361555401.py, line 1)

In [ ]:
import pandas as pd
import json

In [ ]:
sales = pd.read_csv("sales 1.csv")
sales.head()

FileNotFoundError: [Errno 2] No such file or directory: 'sales 1.csv'

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving customers.json to customers.json
Saving products.csv to products.csv
Saving sales 1.csv to sales 1.csv

In [ ]:
import pandas as pd
import json

In [ ]:
sales = pd.read_csv("sales 1.csv")
sales.head()

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09T20:21:00
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28T05:01:00
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13T00:36:00
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,NaN,50.0,2024-07-06T23:39:00
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08T19:58:00

In [ ]:
sales.isnull().sum()

SaleID           0
ProductID        0
CustomerID       0
SalesAmount    497
Quantity       113
Timestamp        0
dtype: int64

In [ ]:
sales.duplicated().sum()

customers.duplicated().sum()

NameError: name 'customers' is not defined

In [ ]:
customers.head()

NameError: name 'customers' is not defined

In [ ]:
import os

print(os.listdir())

['.config', 'ADMM casestudy 2 week 1.zip', 'products.csv', 'customers.json', 'sales 1.csv', 'sample_data']

In [ ]:
import pandas as pd

sales = pd.read_csv("sales 1.csv")

products = pd.read_csv("products.csv")

customers = pd.read_json("customers.json")

print("Sales Shape:", sales.shape)
print("Products Shape:", products.shape)
print("Customers Shape:", customers.shape)

Sales Shape: (10000, 6)
Products Shape: (50, 3)
Customers Shape: (1100, 6)

In [ ]:
customers.head()

  CustomerID FirstName LastName Gender      Region          SSN
0      C0001   Gregory   Miller      M        Ohho    082573197
1      C0002    Marvin     None   male  california  309-6256-21
2      C0003   Gregory    Smith   Male   New Yorkk    407071725
3      C0004    Edward    Davis   male        Ohho  948.18.5740
4      C0005  Reginald   Dawson   male       Texas  975.72.3056

In [ ]:
print(
    "Sales Duplicates:",
    sales.duplicated().sum()
)

print(
    "Customer Duplicates:",
    customers.duplicated().sum()
)

Sales Duplicates: 0
Customer Duplicates: 100

In [ ]:
sales["Timestamp"] = pd.to_datetime(
    sales["Timestamp"]
)

In [ ]:
sales["Revenue"] = (
    sales["SalesAmount"]
    *
    sales["Quantity"]
)

In [ ]:
sales_product = sales.merge(
    products,
    on="ProductID"
)

In [ ]:
retail = sales_product.merge(
    customers,
    on="CustomerID"
)

In [ ]:
retail.head()

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp,Revenue,ProductName,Category,FirstName,LastName,Gender,Region,SSN
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09 20:21:00,29503.80,Keyboard,Electronics,Gina,Woods,Female,california,275/04/1147
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28 05:01:00,7816.62,Smart Glasses,Electronics,James,Ortiz,male,california,603762095
2,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28 05:01:00,7816.62,Smart Glasses,Electronics,James,Ortiz,male,california,603762095
3,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13 00:36:00,83923.28,Headphones,Electronics,Teresa,Martin,female,Ohho,034192490
4,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13 00:36:00,83923.28,Headphones,Electronics,Teresa,Martin,female,Ohho,034192490

In [ ]:
total_revenue = retail[
    "Revenue"
].sum()

print(total_revenue)

411159154.65000004

In [ ]:
retail[
"CustomerID"
].nunique()

1000

In [ ]:
retail.groupby(
"ProductName"
)["Revenue"].sum().sort_values(
ascending=False
).head(10)

ProductName
Action Figure     14225386.82
Kite              14163171.23
Stuffed Animal    14036203.99
Camera            13705201.57
Chair             13378987.73
Board Game        12969070.82
Puzzle            12224890.89
Microwave         12157346.93
Drone             12096258.76
Table             11009816.59
Name: Revenue, dtype: float64

In [ ]:
retail.groupby(
"Region"
)["Revenue"].sum()

Region
Californiya    42317049.20
NY             44890230.23
New York       47323535.08
New Yorkk      39970379.12
Nw York        24043927.95
Ohho           44431278.82
Ohio           32486705.69
Texas          32457153.10
Texaz          39696895.92
california     31517157.40
Name: Revenue, dtype: float64

In [ ]:
clv = retail.groupby(
"CustomerID"
)["Revenue"].sum()

In [ ]:
sales["SalesAmount"] = sales["SalesAmount"].fillna(
    sales["SalesAmount"].median()
)

In [ ]:
sales["Quantity"] = sales["Quantity"].fillna(
    sales["Quantity"].median()
)

In [ ]:
customers = customers.drop_duplicates()

In [ ]:
customers["LastName"] = customers[
    "LastName"
].fillna("Unknown")

In [ ]:
customers["Gender"] = customers[
    "Gender"
].replace({
        "M":"Male",
        "male":"Male",
        "F":"Female",
        "female":"Female"
})

In [ ]:
customers["Region"] = customers[
    "Region"
].replace({
    "Ohho":"Ohio",
    "Nw York":"New York",
    "New Yorkk":"New York",
    "Californiya":"California",
    "Texaz":"Texas",
    "california":"California",
    "NY":"New York"
})

In [ ]:
sales["Timestamp"] = pd.to_datetime(
    sales["Timestamp"]
)

In [ ]:
sales["Revenue"] = (
    sales["SalesAmount"]
    *
    sales["Quantity"]
)

In [ ]:
sales_product = sales.merge(
    products,
    on="ProductID"
)

In [ ]:
retail = sales_product.merge(
    customers,
    on="CustomerID"
)

In [ ]:
retail.head()

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp,Revenue,ProductName,Category,FirstName,LastName,Gender,Region,SSN
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09 20:21:00,29503.80,Keyboard,Electronics,Gina,Woods,Female,California,275/04/1147
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28 05:01:00,7816.62,Smart Glasses,Electronics,James,Ortiz,Male,California,603762095
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13 00:36:00,83923.28,Headphones,Electronics,Teresa,Martin,Female,Ohio,034192490
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,1015.07,50.0,2024-07-06 23:39:00,50753.50,Bluetooth Speaker,Electronics,Ruben,Unknown,Male,Ohio,280.78.2463
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08 19:58:00,1393.56,Mouse,Electronics,Robert,Wiggins,Male,California,029-0509-87

In [ ]:
total_revenue = retail[
    "Revenue"
].sum()

print(total_revenue)

355948745.13

In [ ]:
retail[
"CustomerID"
].nunique()

1000

In [ ]:
retail.groupby(
"ProductName"
)["Revenue"].sum().sort_values(
ascending=False
).head(10)

ProductName
Action Figure     13484962.96
Board Game        12047785.16
Stuffed Animal    10487380.19
Table             10411641.92
Chair             10317745.37
Kite              10246476.87
Camera            10104657.11
Drone             10049903.13
Doll               9218311.26
Microwave          9129707.68
Name: Revenue, dtype: float64

In [ ]:
retail.groupby(
"Region"
)["Revenue"].sum()

Region
California    6.545310e+07
New York      1.373713e+08
Ohio          6.442046e+07
Texas         6.416386e+07
Name: Revenue, dtype: float64

In [ ]:
clv = retail.groupby(
"CustomerID"
)["Revenue"].sum()

In [ ]:
retail.to_csv(
"Fact_Sales.csv",
index=False
)

customers.to_csv(
"Dim_Customer.csv",
index=False
)

products.to_csv(
"Dim_Product.csv",
index=False
)

In [ ]:
from google.colab import files

files.download("Fact_Sales.csv")
files.download("Dim_Customer.csv")
files.download("Dim_Product.csv")

In [ ]:
import os

print(os.listdir())

['.config', 'Fact_Sales.csv', 'Dim_Customer.csv', 'Dim_Product.csv', 'ADMM casestudy 2 week 1.zip', 'products.csv', 'customers.json', 'sales 1.csv', 'sample_data']

In [ ]:
from google.colab import files

files.download("Fact_Sales.csv")

In [ ]:
from google.colab import files

files.download("Fact_Sales.csv")

In [ ]:
files.download("Dim_Product.csv")

In [ ]:
print("Sales Records :", sales.shape[0])

print("Customer Records :", customers.shape[0])

print("Product Records :", products.shape[0])

Sales Records : 10000
Customer Records : 1000
Product Records : 50